services:
  twitch-streamer:
    build: twitch-streamer
    env_file: ".env"
    cap_add:
      - SYS_ADMIN
    environment:
      - DISPLAY=:99
    ports:
      - "9222:9222"
    ipc: host
    shm_size: "2gb"

  diplomacy:
    build: 
      context: ai_animation
      args:
        - VITE_ELEVENLABS_API_KEY=${VITE_ELEVENLABS_API_KEY}
        - VITE_WEBHOOK_URL=${VITE_WEBHOOK_URL}
    env_file: "./ai_animation/.env"
    ports:
      - "4173:4173"
      - "5173:5173"
    volumes:
      - ./ai_animation/public/games/:/app/dist/games
  diplomacy-dev:
    build: ai_animation
    ports:
      - "4173:4173"
      - "5173:5173"
    command: ["npm", "run", "dev-all"]
    volumes:
      - "./ai_animation/:/app/"
